POST http://localhost:3003/api/blogs content-type: application/json Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFydG8iLCJpZCI6IjVhODg2NjNiZjBhZTEzMmQ4MTc2ZjgzZiIsImlhdCI6MTUxODg5NjI3Mn0.RouBHQChsmw-hmAIjEinT9TUQMSUL1SForbt3OUj624

{ "title": "Ethics", "author": "Spinoza", "url": "foo.bar/foobar", "likes": 7, "user": "5a8200895bd1c86a0af1451c" }